config/routes.rb
Bolehnego::Application.routes.draw do

  root :to => "welcome#index"

                        

devise_for :admin, :class_name => 'User', :controllers => {:sessions => 'admin/sessions'} do
  root :to => 'admin#overviews'
end

  namespace :admin do
    resources :overviews
    resources :users do
      put 'changepriv', :on => :member
    end
  end  

  match 'admin/users/:id/changepriv' => 'admin#users#changepriv', :via =>:put

    

end

app/models/ability.rb
class Ability
  include CanCan::Ability

#  def initialize(user)
#    # Define abilities for the passed in user here. For example:
#    #
#    #   user ||= User.new # guest user (not logged in)
#    #   if user.admin?
#    #     can :manage, :all
#    #   else
#    #     can :read, :all
#    #   end
#    #
#    # The first argument to `can` is the action you are giving the user permission to do.
#    # If you pass :manage it will apply to every action. Other common actions here are
#    # :read, :create, :update and :destroy.
#    #
#    # The second argument is the resource the user can perform the action on. If you pass
#    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
#    #
#    # The third argument is an optional hash of conditions to further filter the objects.
#    # For example, here the user can only update published articles.
#    #
#    #   can :update, Article, :published => true
#    #
#    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
#  end
  
  
  
end

app/models/adminability.rb
class AdminAbility
  include CanCan::Ability
  
  def initialize(admin)
    if admin.usertype? :super_admin
      can :manage, :all
      can :read, User
    elsif admin.usertype? :admin
      can :read, :all
    end
  end


end

app/models/user.rb
class User

  include DataMapper::Resource
  #  require 'digest'
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable, :trackable

  storage_names[:default] = "userlogins"
  
  ## Database authenticatable
  property :email,              String, :required => true, :length => 255
  property :encrypted_password, String, :required => true, :field => 'password', :length => 255

  ## Recoverable
  # property :reset_password_token,   String
  # property :reset_password_sent_at, DateTime

  ## Rememberable
  # property :remember_created_at, DateTime

  ## Trackable
  property :sign_in_count,      Integer, :default => 0
  property :current_sign_in_at, DateTime
  property :last_sign_in_at,    DateTime
  property :current_sign_in_ip, String
  property :last_sign_in_ip,    String

  ## Encryptable
  # property :password_salt, String

  ## Confirmable
  # property :confirmation_token,   String
  # property :confirmed_at,         DateTime
  # property :confirmation_sent_at, DateTime
  # property :unconfirmed_email,    String # Only if using reconfirmable

  ## Lockable
  # property :failed_attempts, Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # property :unlock_token,    String # Only if unlock strategy is :email or :both
  # property :locked_at,       DateTime

  ## Token authenticatable
  # property :authentication_token, String, :length => 255

  #  property :id, String, :key => true, :length => 32, :default => lambda {|resource, property| Digest::MD5.hexdigest("#{email}#{Time.now}")  }

  property :id, Serial  
  
  belongs_to :usertype
  

  
  # return userlogin's usertype if no paramater passes, 
  # otherwise it matches userlogin's usertype with the paramater
  
  def usertype?(usertype)
    if usertype
      self.usertype.name==(usertype.to_s.gsub('_','-'))
#     else
#      self.usertype.name
    end
  end
  
end

app/models/userlogin.rb
class Userlogin

  include DataMapper::Resource
  #  require 'digest'
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable, :trackable

  
  
  ## Database authenticatable
  property :email,              String, :required => true, :length => 255
  property :encrypted_password, String, :required => true, :field => 'password', :length => 255

  ## Recoverable
  # property :reset_password_token,   String
  # property :reset_password_sent_at, DateTime

  ## Rememberable
  # property :remember_created_at, DateTime

  ## Trackable
  property :sign_in_count,      Integer, :default => 0
  property :current_sign_in_at, DateTime
  property :last_sign_in_at,    DateTime
  property :current_sign_in_ip, String
  property :last_sign_in_ip,    String

  ## Encryptable
  # property :password_salt, String

  ## Confirmable
  # property :confirmation_token,   String
  # property :confirmed_at,         DateTime
  # property :confirmation_sent_at, DateTime
  # property :unconfirmed_email,    String # Only if using reconfirmable

  ## Lockable
  # property :failed_attempts, Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # property :unlock_token,    String # Only if unlock strategy is :email or :both
  # property :locked_at,       DateTime

  ## Token authenticatable
  # property :authentication_token, String, :length => 255

  #  property :id, String, :key => true, :length => 32, :default => lambda {|resource, property| Digest::MD5.hexdigest("#{email}#{Time.now}")  }

  property :id, Serial  
  
  belongs_to :usertype
  
  # return userlogin's usertype if no paramater passes, 
  # otherwise it matches userlogin's usertype with the paramater
  
  def usertype?(usertype)
    if usertype
      self.usertype.name==(usertype.to_s.gsub('_','-'))
#    else
#      self.usertype.name
    end
  end
  
end

app/models/usertypes.rb
class Usertype
  include DataMapper::Resource
  
  property :id, Integer, :key => true, :min => 0, :max => 11
  property :name, String, :required => true, :length => 255
  
  has n, :users
  
  def show_name
    name = self.name.gsub('-',' ').split.map{|s| s.capitalize}.join(' ')
  end

end

app/controllers/admin/base_controller.rb
require 'dm-rails/middleware/identity_map'
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin!
  
  
  def current_ability
    @current_ability ||= AdminAbility.new(current_admin)
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || admin_overviews_path
  end
  
  
end

app/controllers/admin/overviews_controller.rb
class Admin::OverviewsController < Admin::BaseController
  
   
  def index
    @users = User.all
  
  end
  
  
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController

  layout "admin/login"
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :load_resources
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
    @usertypes = Usertype.all
  end
  
  def create
    @usertypes = Usertype.all
    @user = User.new(params[:user])
    if @user.save
      redirect_to admin_users_path, :notice => '<div class="notice">New User has been added</div>'
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.get(params[:id])
    @usertypes = Usertype.all
  end
  
  def update
    @user = User.get(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html {redirect_to admin_users_path, :notice => '<div class="notice">User has been edited</div>'}
        format.js
      else
        render 'edit'
      end
    end
  end
  
  def destroy
    @user = User.get(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
  
  def changepriv
    @user = User.get(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.js 
      end
    end
  end
  
  def load_resources
    @usertypes = Usertype.all
  end
  

end

app/controllers/application_controller.rb
require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  layout 'welcome'  
  
  def index
  end

end

app/helpers/admin/overviews_helper.rb
module Admin::OverviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin,@user] do |f| %>
  <%= f.label :email %>
  <% if @user.usertype.present? && @user.usertype.name == "admin" || "super-admin" %>  
    <%= @user.email %>
  <% end %>
  <% unless @user.usertype.present? %>
    <%= f.text_field :email %><br/> 
  <% end %>
  <%= f.label :password %>
  <%= f.password_field :password %><br/>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br/>
  <%= f.label :usertype %>
  <%= collection_select(:user, :usertype_id, @usertypes, :id, :show_name, {:include_blank => '---'}) %><br />
  <%= f.submit 'Save' %>
<% end %>

app/views/admin/users/_new_priv.html.erb
<%= link_to @user.usertype.name, "#", :class => "popupTrigger"%>

app/views/admin/users/changepriv.js.erb
$("#changed").replaceWith("<%=j link_to @user.usertype.name, '#', :class => 'popupTrigger' %>");
disablePopup();

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>

<%= render 'form' %>
<%= link_to 'back', admin_users_path%>

app/views/admin/users/index.html.erb
<h1 class="userListHeading">User List</h1>
<hr />
  
<!---Priviledges Edit Pop Up Menu-->

<div id="popupContact"> 
  <p id="contactArea">
  
  <%= form_tag '', :method=> 'put', :class => 'setpriv', :remote => :true do %> 
  <div class="inputset">
    <div class="input">
      <fieldset>
        <select id="user_usertype_id" name="user[usertype_id]" >
          <option class="saPriv" value="1">Super Admin</option>
          <option class="adminPriv" value="2">Admin</option>
          <option class="custPriv" value="3">Customer</option>
        </select>
      </fieldset>
      <p></p>
    </div>
    
  </div> 
		<center><%= submit_tag 'Change' %></center>
	<%end%>
  
  </p>
</div>

<div id="backgroundPopup"></div>

<!---End of Pup Up Menu-->
  
  
<div class="mod table" id="product-list">
  <div class="inner">
    <table id="user-list-table" class="box-table" summary="User List">
      <thead>
        <tr>
          <th scope="col">User ID</th>
          <th scope="col">Email</th>
          <th scope="col">Privilidges</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |u| %>
        <tr>
          <td class="id"><%= u.id %></td>
          <td><%= link_to_if (can? :read, @user),  u.email, edit_admin_user_path(u) %></td>
          <td><%= link_to u.usertype.name, "#", :class => "popupTrigger" %></td>
          <td><%= link_to_if (can? :delete, @user), 'delete', admin_user_path(u), :method => 'delete' %></td>
        </tr>
      <% end %>  
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>
<%= link_to 'back', admin_users_path%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bolehnego</title>
  <%= stylesheet_link_tag    "admin/grid", "admin/reset", "admin/gravity", "admin/text", "admin/style", "admin/form-style", "admin/libraries", "admin/popup" %>
  <%= javascript_include_tag "application", "admin/popup", "jquery.min" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= alert %>

<div class="grid_990 ctr"> 
  <!--TOPMENU & HEADER-->
  
  <div class="topmenu">
    <div class="right panel"> 
      <span class="login_info mrs">Signing as <strong><%= current_admin.email %>(<%= current_admin.usertype.name %>).</strong> | <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></span> 
      <a href="#"> <span class="notification_unactive mrs">0</span>New Message</a> <a href="#">
      <span class="notification_active mrs">3</span>New Orders</a>
    </div>
    <div class="clear"></div>
  </div>
  <div class="header">
    <div class="search_form right">
      <form action="#">      	
          <input type="text" name="search" class="search" value="search product" onfocus="if(this.value == 'search product') {this.value = '';}" onblur="if(this.value==''){this.value = 'search product';}"/>        
      </form>
    </div>
  </div>
  
  <!---> 
  
  <!-LEFT NAV-->  

 <div class="left nav grid_190">
    <ul class="parent">
      <li><%= link_to "Summary", admin_overviews_path %></li>
      <li class="active"><%= link_to "User", admin_users_path %>
        <ul class="child">
          <li><%= link_to_if (can? :update, @users), 'Add Admin', new_admin_user_path %></li>
          <li><%= link_to "Add Customer", "#"%></li>
        </ul>
      </li>
      <li> <%= link_to "Product", "#"%>
        <ul class="child">
          <li><%= link_to "Add Product", "#"%></li>
          <li><%= link_to "Product Category", "#"%></li>
        </ul>
      </li>
      <li><%= link_to "Orders", "#"%>
        <ul class="child">
          <li><%= link_to "Unknown", "#"%></li>
          <li><%= link_to "Unknown", "%"%></li>
          <li><%= link_to "Unknown","#"%></li>
        </ul>
      </li>
      <li><%= link_to "Special Offer", "#"%>
        <ul class="child">
          <li><%= link_to "Add Event", "#"%></li>
          <li><%= link_to "Add Special Offer", "#"%></li>
          <li><%= link_to "Event List", "#"%></li>
        </ul>
      </li>
      <li><%= link_to "Customer Review", "#"%></li>
      <li><%= link_to "Store", "#"%>
        <ul class="child">
          <li><%= link_to "Add Store", "#"%></li>
        </ul>
      </li>
      <li><%= link_to "Manufacter", "#"%>
        <ul class="child">
          <li><%= link_to "Add Manufacter", "#"%></li>
        </ul>
      </li>
      <li><%= link_to "Bolehnego.com Profile", "#"%></li>
    </ul>
  </div>
  
  <!--->
  
  <!-CONTENT-->
  
  <div class="content left grid_780 ml20">  	
  <%= yield %>
  </div>
  
  <!--->

</body>
</html>

app/views/layouts/admin/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bolehnego</title>
  <%= stylesheet_link_tag    "admin/grid", "admin/reset", "admin/gravity", "admin/text", "admin/style", "admin/form-style", "admin/libraries", "admin/popup", %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bolehnego</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bolehnego</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>It's Complicated</h2>